In [1]:
import numpy as np

In [2]:
data = np.random.randn(2,4)
data2 = data * 100 
print('original', data)
print(data2)

original [[ 0.23605601 -2.25153394  1.04877596 -0.71962013]
 [-2.26857921 -0.16031458  1.70148391 -0.86629486]]
[[  23.60560134 -225.15339423  104.87759558  -71.9620132 ]
 [-226.85792093  -16.03145766  170.14839061  -86.62948615]]


In [3]:
# access and mutation work like regular python lists
print(data2[1])
data2[1][1] = 88
print(data2[1])

[-226.85792093  -16.03145766  170.14839061  -86.62948615]
[-226.85792093   88.          170.14839061  -86.62948615]


In [4]:
from_list = np.array([[1,2,3,4], [5,6,7,8]])
print(from_list)
print(from_list.shape)
print(from_list.dtype)
print(from_list.ndim)

[[1 2 3 4]
 [5 6 7 8]]
(2, 4)
int64
2


In [5]:
print(np.zeros((3,2)))

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [6]:
# can create array from native ranges
np.array([list(range(0,10,2)), list(range(1,11,2))])

array([[0, 2, 4, 6, 8],
       [1, 3, 5, 7, 9]])

In [40]:
np.random.choice(['heads', 'tails'], 10, p=[0.7, 0.3])

array(['tails', 'heads', 'heads', 'heads', 'heads', 'tails', 'heads',
       'heads', 'heads', 'heads'], dtype='<U5')

### Not exactly comprehensions, but fromfunction lets you do a lot

In [7]:
def calc(i,j):
    return i + 2 * j

print(np.fromfunction(calc, (2,5), dtype = int))

# or

print(np.fromfunction(lambda i, j: i + 2 *j, (2,5), dtype = int))


[[0 2 4 6 8]
 [1 3 5 7 9]]
[[0 2 4 6 8]
 [1 3 5 7 9]]


### Vector operations make for some clean code

In [34]:
heights_inches = np.array([73, 74, 66]) 
weights_lbs = np.array([135, 225, 201])

heights = heights_inches * 0.0254
weights = weights_lbs * 0.45

bmis = weights / (heights * heights)

print(np.column_stack((heights_inches, weights_lbs, bmis)))

[[ 73.         135.          17.66986082]
 [ 74.         225.          28.65920633]
 [ 66.         201.          32.18498173]]
